server:
  port: 7077

spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle:1521/XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle11gDialect
      show_sql: true
      format_sql: true
