server:
  port: 7077

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/meritz
    username: ${SERVER_MYSQL_USERNAME}
    password: ${SERVER_MYSQL_PASSWORD}
#    dialect: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
